<?php
    $_cartItems = Mage::getSingleton('checkout/cart')->getQuote()->getAllItems()
?>
<?php foreach ($_cartItems as $_item): ?>   
<?php 

$product = Mage::getModel('catalog/product')->load($_item->getProductId());

$cats = $product->getCategoryIds();
$_cats = array();

foreach ($cats as $category_id) {
    $_cat = Mage::getModel('catalog/category')->load($category_id) ;
    if (count($_cats) < 5) {
        $_cats[] = json_encode($_cat->getName());
    }
}

?>
piwikTracker.addEcommerceItem(
    <?php echo json_encode($_item->getSku()) ?>, // (required) SKU: Product unique identifier
    <?php echo json_encode($_item->getName()) ?>, // (optional) Product name
    <?php echo ((empty($_cats) ? '[]' : '['.  implode(',', $_cats).']')) ?>, // (optional) Product category. You can also specify an array of up to 5 categories eg. ["Books", "New releases", "Biography"]
    <?php echo round($_item->getPrice(), 2) ?>, // (recommended) Product price
    <?php echo (int)$_item->getQtyOrdered() ?> // (optional, default to 1) Product quantity
);
<?php endforeach; ?>
piwikTracker.trackEcommerceCartUpdate(<?php echo round(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal(), 2) ?>);
